[package]
name = "ocpi-tariffs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
chrono-tz = "0.7.0"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.27.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"

